-- Verze serveru: 10.4.10-MariaDB


CREATE DATABASE IF NOT EXISTS `wish`;


SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;


START TRANSACTION;

CREATE TABLE `wishes` (
  `id` int(10) UNSIGNED NOT NULL,
  `owner_id` int(10) UNSIGNED NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `wishes`
  ADD PRIMARY KEY (`id`);

COMMIT;
